export { HapticPressProvider, type HapticPressProviderProps } from './HapticPressProvider'
export type { HapticSettings } from './HapticSettingsContext'
export { defaultHapticSettings, HapticSettingsContext } from './HapticSettingsContext'
export { type PaperModuleShape, useHapticPressPaper } from './PaperContext'
export { hapticActions, hapticReducer } from './redux/hapticSlice'
export { type HapticTrigger, type HapticWiring, type HapticWiringEntry, PRESS_WIRING, useHapticHandlers } from './useHapticHandlers'
export { useHapticSettings } from './useHapticSettings'
export { useVibration } from './useVibration'
export { withHaptics } from './withHaptics'

// Native wrappers
export { Pressable, type PressableProps } from './components/native/Pressable'
export { TouchableHighlight, type TouchableHighlightProps } from './components/native/TouchableHighlight'
export { TouchableOpacity, type TouchableOpacityProps } from './components/native/TouchableOpacity'

// Paper wrappers (requires react-native-paper peer dep)
export { AppbarAction, type AppbarActionProps } from './components/paper/AppbarAction'
export { AppbarBackAction, type AppbarBackActionProps } from './components/paper/AppbarBackAction'
export { Button, type ButtonProps } from './components/paper/Button'
export { Card, type CardProps } from './components/paper/Card'
export { Checkbox, type CheckboxProps } from './components/paper/Checkbox'
export { Chip, type ChipProps } from './components/paper/Chip'
export { FAB, type FABProps } from './components/paper/FAB'
export { IconButton, type IconButtonProps } from './components/paper/IconButton'
export { SegmentedButtons, type SegmentedButtonsProps } from './components/paper/SegmentedButtons'
export { Switch, type SwitchProps } from './components/paper/Switch'
export { TouchableRipple, type TouchableRippleProps } from './components/paper/TouchableRipple'
